### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by hatdio** [Dash-Industry-Forum/DASH-IF-Conformance#580]
I installed on an Ubuntu 18.04 LTS, followed the installation guide, but when running a test I get in an XHR Utils/Process.php the folowing:
` PHP Fatal error:  Uncaught Error: Call to a member function addOption() on null in /var/www/html/dash/CMAF/module.php:16\nStack trace:\n#0 /var/www/html/dash/Utils/moduleInterface.php(24): DASHIF\\ModuleCMAF->addCLIArguments()\n#1 /var/www/html/dash/CMAF/module.php(9): DASHIF\\ModuleInterface->__construct()\n#2 /var/www/html/dash/CMAF/module.php(50): DASHIF\\ModuleCMAF->__construct()\n#3 /var/www/html/dash/Utils/Process.php(46): include('/var/www/html/d...')\n#4 {main}\n  thrown in /var/www/html/dash/CMAF/module.php on line 16,`

**Comment by dsilhavy** [comment]
We do not support Ubuntu 18.04 LTS officially, at least our latest modifications are based on Ubuntu 20.04. Do you see the same problem on Ubuntu 20.04?

**Comment by hatdio** [comment]
Hi there, I tried this time on an Ubuntu 20.04 LTS.
I still get the same error "Call to a member function addOption() on null in /var/www/html/DASH-IF-Conformance/CMAF/module.php:16"
I even tried with or without symbolic links.
Perhaps some missing step in installation guide?

**Comment by dsilhavy** [comment]
Thanks for the feedback. Did you try the development branch or the main branch? In case you did not try the main branch can you check that as well. We are currently refactoring the whole code their might be some problems on the development branch.

**Comment by hatdio** [comment]
You mean master right?
I did that but I get empty directory list in Conformance-Frontend (or Conformance-Frontend-HLS)
where are the actual web files?

**Comment by dsilhavy** [comment]
There is a major difference between development and master regarding submodules. With development we moved to a single repo that contains all the different submodules such as Conformance-Frontend and so on. With master these submodules were located in different repositories, for instance https://github.com/Dash-Industry-Forum/Conformance-Frontend/tree/fa43a68b3da00241c2be9841f6fe4110814fa27e.  See also https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/blob/master/.gitmodules 

Can you try:
`git clone --recurse-submodules https://github.com/Dash-Industry-Forum/DASH-IFConformance` and then switch to the master

**Comment by hatdio** [comment]
Trying with `git clone --recurse-submodules https://github.com/Dash-Industry-Forum/DASH-IFConformance`
will ask for username/password and then 'Repository not found'

**Comment by hatdio** [comment]
I suppose url was missing a -
I tried `git clone --recurse-submodules https://github.com/Dash-Industry-Forum/DASH-IF-Conformance`
then `git checkout master`
but again Conformance-Frontend is empty.

**Comment by dsilhavy** [comment]
Try ` git clone --recurse-submodules --branch master https://github.com/Dash-Industry-Forum/DASH-IF-Conformance`

**Comment by hatdio** [comment]
This is working now.
Only difference when checking Segment validation and HbbTV I get error in Repesentations check while on your site Repesentation pass the check.
I am using this mpd:
http://refapp.hbbtv.org/videos/spring_804p_v1/manifest.mpd

**Comment by andyburras** [comment]
I hit the same "Call to a member function addOption() on null" on a development clone done today. I was wanting to track the development code changes for ongoing media validations. Is there a work-around you are using in the development project?
Thanks.

**Comment by dsilhavy** [comment]
@hatdio : Thanks for the observations, we are investigating the segment validation. As we did not make any changes on master as part of the refactoring this seems to be a diff between what is deployed and what is in the master branch.

@andyburras @hatdio The error `Call to a member function addOption() on null` should be gone on development with the latest changes.

**Comment by andyburras** [comment]
That now looks to be fixed. Thanks.
